import type { MetadataCategory } from "../types";

/**
 * XMP is the parallel metadata packet a PDF (and many images) carries beside
 * the Info dictionary. We used to report it as a single "(present)" row, which
 * is enough to justify deleting it but useless to someone who wants to know
 * what is actually in their file.
 *
 * This is a deliberately small reader, not a full RDF parser. XMP in the wild
 * is machine-generated by a handful of writers (Acrobat, Word, Photoshop,
 * scanners) and sticks closely to the same shapes, so pattern matching covers
 * it without pulling in an XML dependency for a client-side bundle.
 */

export interface XmpProperty {
  key: string;
  label: string;
  category: MetadataCategory;
  value: string;
}

/** Properties worth naming, with the category each belongs to. */
const KNOWN: Record<string, { label: string; category: MetadataCategory }> = {
  "dc:title": { label: "XMP title", category: "author" },
  "dc:creator": { label: "XMP author", category: "author" },
  "dc:description": { label: "XMP description", category: "author" },
  "dc:publisher": { label: "XMP publisher", category: "author" },
  "dc:rights": { label: "XMP rights", category: "copyright" },
  "dc:subject": { label: "XMP keywords", category: "custom" },
  "xmp:CreatorTool": { label: "XMP creator tool", category: "software" },
  "xmp:CreateDate": { label: "XMP create date", category: "dates" },
  "xmp:ModifyDate": { label: "XMP modify date", category: "dates" },
  "xmp:MetadataDate": { label: "XMP metadata date", category: "dates" },
  "pdf:Producer": { label: "XMP producer", category: "software" },
  "pdf:Keywords": { label: "XMP keywords", category: "custom" },
  "photoshop:AuthorsPosition": { label: "XMP author title", category: "author" },
  "photoshop:Credit": { label: "XMP credit", category: "copyright" },
  "photoshop:DateCreated": { label: "XMP date created", category: "dates" },
  // Persistent identifiers that survive edits and link copies of a document
  // back to each other, which is exactly what someone anonymising a file wants
  // gone.
  "xmpMM:DocumentID": { label: "XMP document ID", category: "custom" },
  "xmpMM:InstanceID": { label: "XMP instance ID", category: "custom" },
  "xmpMM:OriginalDocumentID": { label: "XMP original document ID", category: "custom" },
  "tiff:Make": { label: "XMP camera make", category: "device" },
  "tiff:Model": { label: "XMP camera model", category: "device" },
};

/** Containers and wrappers that are structure, not content. */
const SKIP_PREFIX = new Set(["rdf", "x", "xmpmeta", "xapMM"]);
const MAX_VALUE = 200;
const MAX_EXTRA = 12;

function decodeEntities(s: string): string {
  return s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, "&"); // last, so a literal &amp;lt; survives intact
}

function clean(raw: string): string {
  const text = decodeEntities(raw).replace(/\s+/g, " ").trim();
  return text.length > MAX_VALUE ? `${text.slice(0, MAX_VALUE)}…` : text;
}

/** Pull the text out of one property body, flattening rdf:Alt / Seq / Bag. */
function valueOf(body: string): string {
  const items = [...body.matchAll(/<rdf:li[^>]*>([\s\S]*?)<\/rdf:li>/g)]
    .map((m) => clean(m[1]))
    .filter(Boolean);
  if (items.length) return items.join(", ");
  if (body.includes("<")) return ""; // a container we don't understand
  return clean(body);
}

export function parseXmp(xml: string): XmpProperty[] {
  const found: XmpProperty[] = [];
  const seen = new Set<string>();

  const take = (key: string, value: string, meta: { label: string; category: MetadataCategory }) => {
    if (!value || seen.has(key)) return;
    seen.add(key);
    found.push({ key, label: meta.label, category: meta.category, value });
  };

  for (const [key, meta] of Object.entries(KNOWN)) {
    // Element form: <dc:creator>…</dc:creator>, possibly wrapping rdf:Seq.
    const el = xml.match(new RegExp(`<${key}(?:\\s[^>]*)?>([\\s\\S]*?)</${key}>`));
    if (el) {
      take(key, valueOf(el[1]), meta);
      continue;
    }
    // Attribute shorthand: <rdf:Description dc:creator="…">
    const attr = xml.match(new RegExp(`\\b${key}\\s*=\\s*"([^"]*)"`)) ??
      xml.match(new RegExp(`\\b${key}\\s*=\\s*'([^']*)'`));
    if (attr) take(key, clean(attr[1]), meta);
  }

  // Anything else with a plain text value, so a viewer shows the whole packet
  // rather than only the fields we happened to anticipate. Bounded, because an
  // unusual writer could otherwise flood the report.
  let extra = 0;
  for (const m of xml.matchAll(/<([A-Za-z][\w]*):([\w]+)(?:\s[^>]*)?>([^<]*)<\/\1:\2>/g)) {
    if (extra >= MAX_EXTRA) break;
    const [, prefix, local, body] = m;
    const key = `${prefix}:${local}`;
    if (KNOWN[key] || seen.has(key) || SKIP_PREFIX.has(prefix)) continue;
    const value = clean(body);
    if (!value) continue;
    seen.add(key);
    found.push({ key, label: `XMP ${local.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase()}`, category: "custom", value });
    extra++;
  }

  return found;
}
